// Mapping of file extensions to languages
export const languageMap = {
  js: "JavaScript",
  jsx: "JavaScript (React)",
  ts: "TypeScript",
  tsx: "TypeScript (React)",

  py: "Python",
  rb: "Ruby",
  php: "PHP",
  sh: "Shell",
  bash: "Shell",
  zsh: "Shell",

  java: "Java",
  kt: "Kotlin",
  cs: "C#",
  cpp: "C++",
  c: "C",
  h: "C/C++ Header",

  swift: "Swift",
  rs: "Rust",
  go: "Go",
  dart: "Dart",

  html: "HTML",
  htm: "HTML",
  css: "CSS",
  scss: "SCSS",
  less: "LESS",
  vue: "Vue",
  svelte: "Svelte",
  handlebars: "Handlebars",
  hbs: "Handlebars",
  ejs: "EJS",
  tsconfig: "TypeScript Config",

  json: "JSON",
  xml: "XML",
  yaml: "YAML",
  yml: "YAML",
  toml: "TOML",

  md: "Markdown",
  markdown: "Markdown",
  txt: "Text",

  sql: "SQL",
  sqlite: "SQLite",
  db: "Database",

  env: "Environment",
  dotenv: "Environment",
  ini: "INI",
  cfg: "Config",
  conf: "Config",
  properties: "Properties",
  plist: "Property List",
  gradle: "Gradle",
  makefile: "Makefile",
  dockerfile: "Dockerfile",
  yml: "YAML",

  bat: "Batch",
  cmd: "Batch",
  ps1: "PowerShell",
  json5: "JSON5",
  lock: "Lock File",
  gitignore: "Git Ignore",
  gitattributes: "Git Attributes",
  markdownlint: "Markdown Lint Config",
  prettierrc: "Prettier Config",
  eslintignore: "ESLint Ignore",
  eslintrc: "ESLint Config",
  stylelintrc: "Stylelint Config",
};
